const trendingItems = [
  {
    id: 1,
    image: "./assets/images/trend8.webp",
    name: "SHOE PALACE NIKE MENS T-SHIRT",
    type: "MENS LIFESTYLE",
    category: "T-SHIRT",
    originalPrice: 25.0,
    price: 14.98,
  },
  {
    id: 2,
    image: "./assets/images/trend1.webp",
    name: "SOLEI VELOUR HOODIE",
    type: "WOMENS",
    category: "HOODIE",
    originalPrice: 60.0,
    price: 35.98,
  },
  {
    id: 3,
    image: "./assets/images/trend2.webp",
    name: "SOLEI VELOUR PANTS",
    type: "WOMENS",
    category: "PANTS",
    originalPrice: 60.0,
    price: 35.98,
  },
  {
    id: 4,
    image: "./assets/images/trend3.webp",
    name: "MESH BASKETBALL",
    type: "MENS",
    category: "SHORTS",
    originalPrice: 60.0,
    price: 19.98,
  },
  {
    id: 5,
    image: "./assets/images/trend4.webp",
    name: "MESH",
    type: "MENS",
    category: "SHORTS",
    originalPrice: 60.0,
    price: 19.98,
  },
  {
    id: 6,
    image: "./assets/images/trend5.webp",
    name: "OLD SKOOL SB",
    type: "MENS LIFESTYLE",
    category: "SHOES",
    originalPrice: 85.0,
    price: 75.98,
  },
  {
    id: 7,
    image: "./assets/images/trend6.webp",
    name: "CHUCK TAYLOR 70 HIGH SNAKE",
    type: "MENS LIFESTYLE",
    category: "SHOES",
    originalPrice: 100.0,
    price: 49.98,
  },
  {
    id: 8,
    image: "./assets/images/trend7.webp",
    name: "KYRIE 5 PATRICK STAR",
    type: "INFANT TODDLER BASKETBALL",
    category: "SHOES",
    originalPrice: 55.0,
    price: 46.98,
  },
];

export default trendingItems;
