export const data = {
  gender: ["men", "women", "kids"],
  price: [
    "$0 - $50",
    "$51 - $100",
    "$101 - $150",
    "$151 - $200",
    "$201 - $400",
    "$401 and up",
  ],
  sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11"],
  color: [
    "Black",
    "White",
    "Blue",
    "Red",
    "Grey",
    "Green",
    "Beige",
    "Brown",
    "Pink",
    "Orange",
    "Purple",
  ],
  brands: [
    "adidas",
    "air jordan",
    "nike",
    "maison article",
    "new balance",
    "Reebok",
    "puma",
  ],
};
//changes needed in womens nike product 1 (img url wrong)
