const shoes = [
  {
    id: 1,
    image: "./assets/images/recom1.webp",
    name: "AIR JORDAN 1 MID GREEN YELLOW",
    type: "MENS LIFESTYLE",
    category: "SHOES",
    price: 125,
  },
  {
    id: 2,
    image: "./assets/images/recom2.webp",
    name: "AIR JORDAN 1 MID TIE DYE",
    type: "MENS LIFESTYLE",
    category: "SHOES",
    price: 135,
  },
  {
    id: 3,
    image: "./assets/images/recom3.webp",
    name: "AIR JORDAN 5 RETRO GREEN BEAN",
    type: "MENS LIFESTYLE",
    category: "SHOES",
    price: 200,
  },
  {
    id: 4,
    image: "./assets/images/recom4.webp",
    name: "AIR JORDAN 11 RETRO LOW 72-10",
    type: "GRADE SCHOOL LIFESTYLE",
    category: "SHOES",
    price: 135,
  },
  {
    id: 5,
    image: "./assets/images/recom5.webp",
    name: "AIR JORDAN 1 MID NEWSPRINT",
    type: "WOMENS LIFESTYLE",
    category: "SHOES",
    price: 135,
  },
  {
    id: 6,
    image: "./assets/images/recom6.webp",
    name: "AIR JORDAN 5 RETRO REGAL PINK",
    type: "MENS LIFESTYLE",
    category: "SHOES",
    price: 210,
  },
  {
    id: 7,
    image: "./assets/images/recom7.webp",
    name: "AIR JORDAN 1 HIGH OG HERITAGE",
    type: "GRADE SCHOOL LIFESTYLE",
    category: "SHOES",
    price: 130,
  },
  {
    id: 8,
    image: "./assets/images/recom8.webp",
    name: "AIR JORDAN 1 HIGH OG BROTHERHOOD",
    type: "MENS LIFESTYLE",
    category: "SHOES",
    price: 180,
  },
  {
    id: 9,
    image: "./assets/images/recom9.webp",
    name: "AIR JORDAN 1 MID BLACK + RED= BRED",
    type: "GRADE SCHOOL LIFESTYLE",
    category: "SHOES",
    price: 110,
  },
  {
    id: 10,
    image: "./assets/images/recom10.webp",
    name: "AIR JORDAN 1 MID REVERSE BRED",
    type: "GRADE SCHOOL LIFESTYLE",
    category: "SHOES",
    price: 100,
  },
];

export default shoes;
